id: I69F168AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:47:50+00:00'
last_modified: '2022-06-08T05:37:03.451661+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4573
  title: ས་སྐྱ་གོང་མ་རྣམ་ལྔའི་གསུང་འབུམ་ཁ་སྐོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7E09:
      image_group_id: I1PD34029
      title: ''
      total_pages: 370
      order: 1
      base_file: 7E09.txt
    '7329':
      image_group_id: I1PD34030
      title: ''
      total_pages: 408
      order: 2
      base_file: 7329.txt
    A305:
      image_group_id: I1PD34031
      title: ''
      total_pages: 470
      order: 3
      base_file: A305.txt
    022C:
      image_group_id: I1PD34032
      title: ''
      total_pages: 462
      order: 4
      base_file: 022C.txt
    0894:
      image_group_id: I1PD34033
      title: ''
      total_pages: 258
      order: 5
      base_file: 0894.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
